pipeline:
  build:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: publicintegrity/loader

  test:
    image: publicintegrity/loader
    pull: true
    commands:
      - node --version
      - npm --version
      - python --version
      - wget --version
      - bash --version
      - psql --version

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
